[tool.poetry]
name = "slicereg"
version = "0.1.0"
description = "A 2D-3D histological brain slice registration application for mouse brains."
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8.1,<3.9"
tifffile = "^2020.12.8"
xmltodict = "^0.12.0"
numpy = "^1.21.0"
bg-atlasapi = "^1.0.0"
PySide2 = "~5.14"  # Pyside 5.15.2 is not working properly with CI
PyOpenGL = "^3.1.5"
PyOpenGL-accelerate = "^3.1.5"
vispy = "^0.6.0"
numba = "^0.53.0"
imio = "^0.0.5"
packaging = "^20.9"
result = "^0.6.0"

[tool.poetry.dev-dependencies]
dvc = { extras = ["gdrive"], version = "^2.0" }
pywin32 = {version = "225", platform = "win32"}
pytest = "^6.2.1"
pytest-qt = "^3.3.0"
pytest-bdd = "^4.0.2"
pytest-env = "^0.6.2"
hypothesis = "^6.0.0"
coverage = {extras = ["toml"], version = "^5.3.1"}
mypy = "^0.812"
rope = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bg-slicereg = "slicereg.main:launch_gui"

[tool.coverage.run]
relative_files = true

[tool.pytest.ini_options]
env = "NUMBA_DISABLE_JIT=1"
markers = [
    "gui: mark a test as using qt libraries"
]
addopts = "--doctest-modules"
filterwarnings = [
    "ignore::DeprecationWarning"
]
